//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADONETWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int ApptID { get; set; }
        public string AppointmentDate { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> HRID { get; set; }
        public string Slot { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
